<a href="https://colab.research.google.com/github/anyelakaterine/practica-pandas-python/blob/main/Taller-pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# =========================================================
# TALLER PRACTICO PANDAS + EXCEL
# ANYELA KATERINE RENTERIA CUAMA
# GOOGLE COLAB
# =========================================================

# Importamos la herramienta files de Google Colab
# para poder subir archivos Excel
from google.colab import files

# Subimos el archivo Excel al entorno de Colab
uploaded = files.upload()

# =========================================================
# IMPORTAR LIBRERIA
# =========================================================

# Importamos la librería pandas
# para trabajar con tablas y datos
import pandas as pd

In [ ]:
# =========================================================
# LEER ARCHIVO EXCEL
# =========================================================

# Leemos el archivo Excel cargado
# y lo guardamos en el DataFrame df
df = pd.read_excel(next(iter(uploaded)))

In [ ]:
# =========================================================
# MOSTRAR DATAFRAME
# =========================================================

# Imprimimos una línea decorativa
print("===================================")

# Mostramos el título
print("DATAFRAME COMPLETO")

# Imprimimos otra línea decorativa
print("===================================")

# Mostramos el DataFrame completo
display(df)

===================================
DATAFRAME COMPLETO
===================================

,Producto,Precio,Cantidad,Costo_Envio,Categoria,Total_Venta,Costo_Total,IVA,Ganancia_Estimada,Perdida_Estimada,Porcentaje_Ventas
0,Laptop,3500000,4,50000,Tecnología,14000000,14050000,2660000.0,3500000.0,700000.0,3.798670
1,Mouse,80000,15,10000,Tecnología,1200000,1210000,228000.0,300000.0,60000.0,0.325600
2,Teclado,120000,10,12000,Tecnología,1200000,1212000,228000.0,300000.0,60000.0,0.325600
3,Silla,450000,5,30000,Oficina,2250000,2280000,427500.0,562500.0,112500.0,0.610501
4,Escritorio,900000,3,40000,Oficina,2700000,2740000,513000.0,675000.0,135000.0,0.732601
5,Monitor,1100000,6,35000,Tecnología,6600000,6635000,1254000.0,1650000.0,330000.0,1.790802
6,Impresora,700000,7,25000,Tecnología,4900000,4925000,931000.0,1225000.0,245000.0,1.329535
7,Celular,2500000,8,45000,Tecnología,20000000,20045000,3800000.0,5000000.0,1000000.0,5.426672
8,Audifonos,150000,12,10000,Tecnología,1800000,1810000,342000.0,450000.0,90000.0,0.488400
9,Camara,1800000,4,40000,Tecnología,7200000,7240000,1368000.0,1800000.0,360000.0,1.953602
10,Router,300000,10,15000,Tecnología,3000000,3015000,570000.0,750000.0,150000.0,0.814001
11,Microfono,250000,6,12000,Tecnología,1500000,1512000,285000.0,375000.0,75000.0,0.407000
12,Parlantes,400000,7,18000,Tecnología,2800000,2818000,532000.0,700000.0,140000.0,0.759734
13,Disco Duro,500000,9,20000,Tecnología,4500000,4520000,855000.0,1125000.0,225000.0,1.221001
14,Memoria USB,50000,20,5000,Tecnología,1000000,1005000,190000.0,250000.0,50000.0,0.271334
15,Smartwatch,900000,5,25000,Tecnología,4500000,4525000,855000.0,1125000.0,225000.0,1.221001
16,Proyector,2000000,3,50000,Tecnología,6000000,6050000,1140000.0,1500000.0,300000.0,1.628002
17,Switch,350000,6,15000,Tecnología,2100000,2115000,399000.0,525000.0,105000.0,0.569801
18,Servidor,7000000,2,80000,Tecnología,14000000,14080000,2660000.0,3500000.0,700000.0,3.798670
19,Webcam,180000,11,10000,Tecnología,1980000,1990000,376200.0,495000.0,99000.0,0.537241
20,Cargador,70000,14,7000,Tecnología,980000,987000,186200.0,245000.0,49000.0,0.265907
21,Drone,4500000,2,60000,Tecnología,9000000,9060000,1710000.0,2250000.0,450000.0,2.442002
22,CPU,2200000,5,35000,Tecnología,11000000,11035000,2090000.0,2750000.0,550000.0,2.984670
23,Tarjeta Grafica,3200000,4,45000,Tecnología,12800000,12845000,2432000.0,3200000.0,640000.0,3.473070
24,Procesador,1800000,6,30000,Tecnología,10800000,10830000,2052000.0,2700000.0,540000.0,2.930403
25,Fuente Poder,450000,8,12000,Tecnología,3600000,3612000,684000.0,900000.0,180000.0,0.976801
26,Ventilador PC,120000,15,8000,Tecnología,1800000,1808000,342000.0,450000.0,90000.0,0.488400
27,SSD,600000,10,15000,Tecnología,6000000,6015000,1140000.0,1500000.0,300000.0,1.628002
28,RAM,350000,12,10000,Tecnología,4200000,4210000,798000.0,1050000.0,210000.0,1.139601
29,Cable HDMI,40000,25,3000,Tecnología,1000000,1003000,190000.0,250000.0,50000.0,0.271334
30,Cable USB,30000,30,3000,Tecnología,900000,903000,171000.0,225000.0,45000.0,0.244200
31,Mouse Pad,25000,18,2000,Tecnología,450000,452000,85500.0,112500.0,22500.0,0.122100
32,Silla Gamer,850000,4,35000,Oficina,3400000,3435000,646000.0,850000.0,170000.0,0.922534
33,Mesa Gamer,1200000,3,45000,Oficina,3600000,3645000,684000.0,900000.0,180000.0,0.976801
34,Pantalla LED,1500000,5,40000,Tecnología,7500000,7540000,1425000.0,1875000.0,375000.0,2.035002
35,Joystick,350000,8,12000,Tecnología,2800000,2812000,532000.0,700000.0,140000.0,0.759734
36,Consola,2800000,4,50000,Tecnología,11200000,11250000,2128000.0,2800000.0,560000.0,3.038936
37,Laptop Gamer,6500000,2,70000,Tecnología,13000000,13070000,2470000.0,3250000.0,650000.0,3.527337
38,MacBook,8000000,2,80000,Tecnología,16000000,16080000,3040000.0,4000000.0,800000.0,4.341338
39,iPad,4500000,3,60000,Tecnología,13500000,13560000,2565000.0,3375000.0,675000.0,3.663004
40,iPhone,5500000,4,65000,Tecnología,22000000,22065000,4180000.0,5500000.0,1100000.0,5.969339
41,Samsung TV,3200000,3,45000,Tecnología,9600000,9645000,1824000.0,2400000.0,480000.0,2.604803
42,Alexa,250000,10,10000,Tecnología,2500000,2510000,475000.0,625000.0,125000.0,0.678334
43,Google Home,300000,8,12000,Tecnología,2400000,2412000,456000.0,600000.0,120000.0,0.651201
44,Apple Watch,1800000,5,30000,Tecnología,9000000,9030000,1710000.0,2250000.0,450000.0,2.442002
45,Xbox,2500000,4,45000,Tecnología,10000000,10045000,1900000.0,2500000.0,500000.0,2.713336
46,PlayStation,3000000,3,50000,Tecnología,9000000,9050000,1710000.0,2250000.0,450000.0,2.442002
47,Nintendo Switch,2200000,5,40000,Tecnología,11000000,11040000,2090000.0,2750000.0,550000.0,2.984670
48,Monitor Curvo,1700000,6,38000,Tecnología,10200000,10238000,1938000.0,2550000.0,510000.0,2.767603
49,Teclado Gamer,200000,9,12000,Tecnología,1800000,1812000,342000.0,450000.0,90000.0,0.488400
50,Mouse Gamer,180000,11,12000,Tecnología,1980000,1992000,376200.0,495000.0,99000.0,0.537241
51,Camara Web HD,250000,7,18000,Tecnología,1750000,1768000,332500.0,437500.0,87500.0,0.474834
52,Escaner,600000,5,25000,Tecnología,3000000,3025000,570000.0,750000.0,150000.0,0.814001
53,UPS,900000,3,30000,Tecnología,2700000,2730000,513000.0,675000.0,135000.0,0.732601
54,Servidor Dell,8500000,2,85000,Tecnología,17000000,17085000,3230000.0,4250000.0,850000.0,4.612671
55,Router TP-Link,450000,8,15000,Tecnología,3600000,3615000,684000.0,900000.0,180000.0,0.976801
56,Impresora HP,750000,6,28000,Tecnología,4500000,4528000,855000.0,1125000.0,225000.0,1.221001
57,Tablet Lenovo,1300000,4,32000,Tecnología,5200000,5232000,988000.0,1300000.0,260000.0,1.410935
58,Bocina Bluetooth,280000,7,15000,Tecnología,1960000,1975000,372400.0,490000.0,98000.0,0.531814
59,Lector Codigo Barras,520000,5,18000,Tecnología,2600000,2618000,494000.0,650000.0,130000.0,0.705467

In [ ]:
# =========================================================
# PRIMERAS 5 FILAS
# =========================================================

# Hacemos un salto de línea y mostramos título
print("\n===================================")

# Mostramos subtítulo
print("PRIMERAS 5 FILAS")

# Línea decorativa
print("===================================")

# Mostramos las primeras 5 filas
display(df.head())

===================================
PRIMERAS 5 FILAS
===================================

,Producto,Precio,Cantidad,Costo_Envio,Categoria,Total_Venta,Costo_Total,IVA,Ganancia_Estimada,Perdida_Estimada,Porcentaje_Ventas
0,Laptop,3500000,4,50000,Tecnología,14000000,14050000,2660000.0,3500000.0,700000.0,3.798670
1,Mouse,80000,15,10000,Tecnología,1200000,1210000,228000.0,300000.0,60000.0,0.325600
2,Teclado,120000,10,12000,Tecnología,1200000,1212000,228000.0,300000.0,60000.0,0.325600
3,Silla,450000,5,30000,Oficina,2250000,2280000,427500.0,562500.0,112500.0,0.610501
4,Escritorio,900000,3,40000,Oficina,2700000,2740000,513000.0,675000.0,135000.0,0.732601

In [ ]:
# =========================================================
# ULTIMAS 10 FILAS
# =========================================================

# Mostramos línea decorativa
print("\n===================================")

# Mostramos subtítulo
print("ULTIMAS 10 FILAS")

# Mostramos línea decorativa
print("===================================")

# Mostramos las últimas 10 filas
display(df.tail(10))

===================================
ULTIMAS 10 FILAS
===================================

,Producto,Precio,Cantidad,Costo_Envio,Categoria,Total_Venta,Costo_Total,IVA,Ganancia_Estimada,Perdida_Estimada,Porcentaje_Ventas
50,Mouse Gamer,180000,11,12000,Tecnología,1980000,1992000,376200.0,495000.0,99000.0,0.537241
51,Camara Web HD,250000,7,18000,Tecnología,1750000,1768000,332500.0,437500.0,87500.0,0.474834
52,Escaner,600000,5,25000,Tecnología,3000000,3025000,570000.0,750000.0,150000.0,0.814001
53,UPS,900000,3,30000,Tecnología,2700000,2730000,513000.0,675000.0,135000.0,0.732601
54,Servidor Dell,8500000,2,85000,Tecnología,17000000,17085000,3230000.0,4250000.0,850000.0,4.612671
55,Router TP-Link,450000,8,15000,Tecnología,3600000,3615000,684000.0,900000.0,180000.0,0.976801
56,Impresora HP,750000,6,28000,Tecnología,4500000,4528000,855000.0,1125000.0,225000.0,1.221001
57,Tablet Lenovo,1300000,4,32000,Tecnología,5200000,5232000,988000.0,1300000.0,260000.0,1.410935
58,Bocina Bluetooth,280000,7,15000,Tecnología,1960000,1975000,372400.0,490000.0,98000.0,0.531814
59,Lector Codigo Barras,520000,5,18000,Tecnología,2600000,2618000,494000.0,650000.0,130000.0,0.705467

In [ ]:
# =========================================================
# TIPOS DE DATOS DE CADA COLUMNA
# =========================================================

# Mostramos línea decorativa
print("\n===================================")

# Mostramos subtítulo
print("TIPOS DE DATOS DE CADA COLUMNA")

# Mostramos línea decorativa
print("===================================")

# Mostramos el tipo de dato
# de cada columna del DataFrame
display(df.dtypes)

===================================
TIPOS DE DATOS DE CADA COLUMNA
===================================

Producto              object
Precio                 int64
Cantidad               int64
Costo_Envio            int64
Categoria             object
Total_Venta            int64
Costo_Total            int64
IVA                  float64
Ganancia_Estimada    float64
Perdida_Estimada     float64
Porcentaje_Ventas    float64
dtype: object

In [ ]:
# =========================================================
# TAMAÑO DEL DATAFRAME
# =========================================================

# Mostramos línea decorativa
print("\n===================================")

# Mostramos subtítulo
print("TAMAÑO DEL DATAFRAME")

# Mostramos línea decorativa
print("===================================")

# Mostramos cantidad de filas
print("Cantidad de filas:")
print(df.shape[0])

# Mostramos cantidad de columnas
print("\nCantidad de columnas:")
print(df.shape[1])

===================================
TAMAÑO DEL DATAFRAME
===================================
Cantidad de filas:
60

Cantidad de columnas:

11

In [ ]:
# =========================================================
# DESCRIPCION ESTADISTICA
# =========================================================

# Mostramos línea decorativa
print("\n===================================")

# Mostramos subtítulo
print("DESCRIPCION ESTADISTICA")

# Mostramos línea decorativa
print("===================================")

# Mostramos estadísticas descriptivas
display(df.describe())

===================================
DESCRIPCION ESTADISTICA
===================================

,Precio,Cantidad,Costo_Envio,Total_Venta,Costo_Total,IVA,Ganancia_Estimada,Perdida_Estimada,Porcentaje_Ventas
count,6.000000e+01,60.000000,60.000000,6.000000e+01,6.000000e+01,6.000000e+01,6.000000e+01,6.000000e+01,60.000000
mean,1.611583e+06,7.466667,29900.000000,6.142500e+06,6.172400e+06,1.167075e+06,1.535625e+06,3.071250e+05,1.666667
std,2.035978e+06,5.500282,20912.002879,5.222429e+06,5.240130e+06,9.922615e+05,1.305607e+06,2.611214e+05,1.417020
min,2.500000e+04,2.000000,2000.000000,4.500000e+05,4.520000e+05,8.550000e+04,1.125000e+05,2.250000e+04,0.122100
25%,2.725000e+05,4.000000,12000.000000,2.070000e+06,2.084250e+06,3.933000e+05,5.175000e+05,1.035000e+05,0.561661
50%,7.250000e+05,6.000000,26500.000000,3.900000e+06,3.927500e+06,7.410000e+05,9.750000e+05,1.950000e+05,1.058201
75%,2.200000e+06,9.250000,45000.000000,9.700000e+06,9.745000e+06,1.843000e+06,2.425000e+06,4.850000e+05,2.631936
max,8.500000e+06,30.000000,85000.000000,2.200000e+07,2.206500e+07,4.180000e+06,5.500000e+06,1.100000e+06,5.969339

In [ ]:
# =========================================================
# CREAR TOTAL_VENTA
# =========================================================

# Multiplicamos la columna Precio
# por la columna Cantidad
df['Total_Venta'] = df['Precio'] * df['Cantidad']

# Mostramos línea decorativa
print("\n===================================")

# Mostramos subtítulo
print("TOTAL_VENTA")

# Mostramos línea decorativa
print("===================================")

# Mostramos columnas seleccionadas
display(df[['Producto', 'Total_Venta']])

===================================
TOTAL_VENTA
===================================

                Producto  Total_Venta
0                 Laptop     14000000
1                  Mouse      1200000
2                Teclado      1200000
3                  Silla      2250000
4             Escritorio      2700000
5                Monitor      6600000
6              Impresora      4900000
7                Celular     20000000
8              Audifonos      1800000
9                 Camara      7200000
10                Router      3000000
11             Microfono      1500000
12             Parlantes      2800000
13            Disco Duro      4500000
14           Memoria USB      1000000
15            Smartwatch      4500000
16             Proyector      6000000
17                Switch      2100000
18              Servidor     14000000
19                Webcam      1980000
20              Cargador       980000
21                 Drone      9000000
22                   CPU     11000000
23       Tarjeta Grafica     12800000
24            Procesador     10800000
25          Fuente Poder      3600000
26         Ventilador PC      1800000
27                   SSD      6000000
28                   RAM      4200000
29            Cable HDMI      1000000
30             Cable USB       900000
31             Mouse Pad       450000
32           Silla Gamer      3400000
33            Mesa Gamer      3600000
34          Pantalla LED      7500000
35              Joystick      2800000
36               Consola     11200000
37          Laptop Gamer     13000000
38               MacBook     16000000
39                  iPad     13500000
40                iPhone     22000000
41            Samsung TV      9600000
42                 Alexa      2500000
43           Google Home      2400000
44           Apple Watch      9000000
45                  Xbox     10000000
46           PlayStation      9000000
47       Nintendo Switch     11000000
48         Monitor Curvo     10200000
49         Teclado Gamer      1800000
50           Mouse Gamer      1980000
51         Camara Web HD      1750000
52               Escaner      3000000
53                   UPS      2700000
54         Servidor Dell     17000000
55        Router TP-Link      3600000
56          Impresora HP      4500000
57         Tablet Lenovo      5200000
58      Bocina Bluetooth      1960000
59  Lector Codigo Barras      2600000

In [ ]:
# =========================================================
# CREAR COSTO_TOTAL
# =========================================================

# Sumamos Total_Venta y Costo_Envio
df['Costo_Total'] = df['Total_Venta'] + df['Costo_Envio']

# Mostramos línea decorativa
print("\n===================================")

# Mostramos subtítulo
print("COSTO_TOTAL")

# Mostramos línea decorativa
print("===================================")

# Mostramos columnas seleccionadas
display(df[['Producto', 'Costo_Total']])

===================================
COSTO_TOTAL
===================================

                Producto  Costo_Total
0                 Laptop     14050000
1                  Mouse      1210000
2                Teclado      1212000
3                  Silla      2280000
4             Escritorio      2740000
5                Monitor      6635000
6              Impresora      4925000
7                Celular     20045000
8              Audifonos      1810000
9                 Camara      7240000
10                Router      3015000
11             Microfono      1512000
12             Parlantes      2818000
13            Disco Duro      4520000
14           Memoria USB      1005000
15            Smartwatch      4525000
16             Proyector      6050000
17                Switch      2115000
18              Servidor     14080000
19                Webcam      1990000
20              Cargador       987000
21                 Drone      9060000
22                   CPU     11035000
23       Tarjeta Grafica     12845000
24            Procesador     10830000
25          Fuente Poder      3612000
26         Ventilador PC      1808000
27                   SSD      6015000
28                   RAM      4210000
29            Cable HDMI      1003000
30             Cable USB       903000
31             Mouse Pad       452000
32           Silla Gamer      3435000
33            Mesa Gamer      3645000
34          Pantalla LED      7540000
35              Joystick      2812000
36               Consola     11250000
37          Laptop Gamer     13070000
38               MacBook     16080000
39                  iPad     13560000
40                iPhone     22065000
41            Samsung TV      9645000
42                 Alexa      2510000
43           Google Home      2412000
44           Apple Watch      9030000
45                  Xbox     10045000
46           PlayStation      9050000
47       Nintendo Switch     11040000
48         Monitor Curvo     10238000
49         Teclado Gamer      1812000
50           Mouse Gamer      1992000
51         Camara Web HD      1768000
52               Escaner      3025000
53                   UPS      2730000
54         Servidor Dell     17085000
55        Router TP-Link      3615000
56          Impresora HP      4528000
57         Tablet Lenovo      5232000
58      Bocina Bluetooth      1975000
59  Lector Codigo Barras      2618000

In [ ]:
# =========================================================
# PROMEDIO
# =========================================================

# Calculamos promedio de Total_Venta
promedio = df['Total_Venta'].mean()

# Mostramos línea decorativa
print("\n===================================")

# Mostramos subtítulo
print("PROMEDIO TOTAL_VENTA")

# Mostramos línea decorativa
print("===================================")

# Mostramos promedio
print(promedio)

===================================
PROMEDIO TOTAL_VENTA
===================================
6142500.0

In [ ]:
# =========================================================
# PRODUCTO MAYOR VENTA
# =========================================================

# Buscamos el producto
# con mayor Total_Venta
producto_mayor = df.loc[df['Total_Venta'].idxmax()]

# Mostramos línea decorativa
print("\n===================================")

# Mostramos subtítulo
print("PRODUCTO MAYOR VENTA")

# Mostramos línea decorativa
print("===================================")

# Mostramos resultado
display(producto_mayor)

===================================
PRODUCTO MAYOR VENTA
===================================

Producto                 iPhone
Precio                  5500000
Cantidad                      4
Costo_Envio               65000
Categoria            Tecnología
Total_Venta            22000000
Costo_Total            22065000
IVA                   4180000.0
Ganancia_Estimada     5500000.0
Perdida_Estimada      1100000.0
Porcentaje_Ventas      5.969339
Name: 40, dtype: object

In [ ]:
# =========================================================
# PRODUCTO MENOR VENTA
# =========================================================

# Buscamos el producto
# con menor Total_Venta
producto_menor = df.loc[df['Total_Venta'].idxmin()]

# Mostramos línea decorativa
print("\n===================================")

# Mostramos subtítulo
print("PRODUCTO MENOR VENTA")

# Mostramos línea decorativa
print("===================================")

# Mostramos resultado
display(producto_menor)

===================================
PRODUCTO MENOR VENTA
===================================

Producto        Mouse Pad
Precio              25000
Cantidad               18
Costo_Envio          2000
Categoria      Tecnología
Total_Venta        450000
Costo_Total        452000
Name: 31, dtype: object

In [ ]:
# =========================================================
# CREAR COLUMNA IVA
# =========================================================

# Se crea una nueva columna llamada IVA
# El IVA corresponde al 19% del Total_Venta
df['IVA'] = df['Total_Venta'] * 0.19

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("COLUMNA IVA")

# Línea decorativa
print("===================================")

# Mostramos Producto, Total_Venta e IVA
display(df[['Producto', 'Total_Venta', 'IVA']])

===================================
COLUMNA IVA
===================================

                Producto  Total_Venta        IVA
0                 Laptop     14000000  2660000.0
1                  Mouse      1200000   228000.0
2                Teclado      1200000   228000.0
3                  Silla      2250000   427500.0
4             Escritorio      2700000   513000.0
5                Monitor      6600000  1254000.0
6              Impresora      4900000   931000.0
7                Celular     20000000  3800000.0
8              Audifonos      1800000   342000.0
9                 Camara      7200000  1368000.0
10                Router      3000000   570000.0
11             Microfono      1500000   285000.0
12             Parlantes      2800000   532000.0
13            Disco Duro      4500000   855000.0
14           Memoria USB      1000000   190000.0
15            Smartwatch      4500000   855000.0
16             Proyector      6000000  1140000.0
17                Switch      2100000   399000.0
18              Servidor     14000000  2660000.0
19                Webcam      1980000   376200.0
20              Cargador       980000   186200.0
21                 Drone      9000000  1710000.0
22                   CPU     11000000  2090000.0
23       Tarjeta Grafica     12800000  2432000.0
24            Procesador     10800000  2052000.0
25          Fuente Poder      3600000   684000.0
26         Ventilador PC      1800000   342000.0
27                   SSD      6000000  1140000.0
28                   RAM      4200000   798000.0
29            Cable HDMI      1000000   190000.0
30             Cable USB       900000   171000.0
31             Mouse Pad       450000    85500.0
32           Silla Gamer      3400000   646000.0
33            Mesa Gamer      3600000   684000.0
34          Pantalla LED      7500000  1425000.0
35              Joystick      2800000   532000.0
36               Consola     11200000  2128000.0
37          Laptop Gamer     13000000  2470000.0
38               MacBook     16000000  3040000.0
39                  iPad     13500000  2565000.0
40                iPhone     22000000  4180000.0
41            Samsung TV      9600000  1824000.0
42                 Alexa      2500000   475000.0
43           Google Home      2400000   456000.0
44           Apple Watch      9000000  1710000.0
45                  Xbox     10000000  1900000.0
46           PlayStation      9000000  1710000.0
47       Nintendo Switch     11000000  2090000.0
48         Monitor Curvo     10200000  1938000.0
49         Teclado Gamer      1800000   342000.0
50           Mouse Gamer      1980000   376200.0
51         Camara Web HD      1750000   332500.0
52               Escaner      3000000   570000.0
53                   UPS      2700000   513000.0
54         Servidor Dell     17000000  3230000.0
55        Router TP-Link      3600000   684000.0
56          Impresora HP      4500000   855000.0
57         Tablet Lenovo      5200000   988000.0
58      Bocina Bluetooth      1960000   372400.0
59  Lector Codigo Barras      2600000   494000.0

In [ ]:
# =========================================================
# CREAR COLUMNA GANANCIA_ESTIMADA
# =========================================================

# Se calcula una ganancia estimada del 25%
# tomando como base el Total_Venta
df['Ganancia_Estimada'] = df['Total_Venta'] * 0.25

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("GANANCIA ESTIMADA")

# Línea decorativa
print("===================================")

# Mostramos Producto y Ganancia_Estimada
display(df[['Producto', 'Ganancia_Estimada']])

===================================
GANANCIA ESTIMADA
===================================

                Producto  Ganancia_Estimada
0                 Laptop          3500000.0
1                  Mouse           300000.0
2                Teclado           300000.0
3                  Silla           562500.0
4             Escritorio           675000.0
5                Monitor          1650000.0
6              Impresora          1225000.0
7                Celular          5000000.0
8              Audifonos           450000.0
9                 Camara          1800000.0
10                Router           750000.0
11             Microfono           375000.0
12             Parlantes           700000.0
13            Disco Duro          1125000.0
14           Memoria USB           250000.0
15            Smartwatch          1125000.0
16             Proyector          1500000.0
17                Switch           525000.0
18              Servidor          3500000.0
19                Webcam           495000.0
20              Cargador           245000.0
21                 Drone          2250000.0
22                   CPU          2750000.0
23       Tarjeta Grafica          3200000.0
24            Procesador          2700000.0
25          Fuente Poder           900000.0
26         Ventilador PC           450000.0
27                   SSD          1500000.0
28                   RAM          1050000.0
29            Cable HDMI           250000.0
30             Cable USB           225000.0
31             Mouse Pad           112500.0
32           Silla Gamer           850000.0
33            Mesa Gamer           900000.0
34          Pantalla LED          1875000.0
35              Joystick           700000.0
36               Consola          2800000.0
37          Laptop Gamer          3250000.0
38               MacBook          4000000.0
39                  iPad          3375000.0
40                iPhone          5500000.0
41            Samsung TV          2400000.0
42                 Alexa           625000.0
43           Google Home           600000.0
44           Apple Watch          2250000.0
45                  Xbox          2500000.0
46           PlayStation          2250000.0
47       Nintendo Switch          2750000.0
48         Monitor Curvo          2550000.0
49         Teclado Gamer           450000.0
50           Mouse Gamer           495000.0
51         Camara Web HD           437500.0
52               Escaner           750000.0
53                   UPS           675000.0
54         Servidor Dell          4250000.0
55        Router TP-Link           900000.0
56          Impresora HP          1125000.0
57         Tablet Lenovo          1300000.0
58      Bocina Bluetooth           490000.0
59  Lector Codigo Barras           650000.0

In [ ]:
# =========================================================
# CREAR COLUMNA PERDIDA_ESTIMADA
# =========================================================

# Se calcula una pérdida estimada del 5%
# basada en el Total_Venta
df['Perdida_Estimada'] = df['Total_Venta'] * 0.05

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("PERDIDA ESTIMADA")

# Línea decorativa
print("===================================")

# Mostramos Producto y Perdida_Estimada
display(df[['Producto', 'Perdida_Estimada']])

===================================
PERDIDA ESTIMADA
===================================

                Producto  Perdida_Estimada
0                 Laptop          700000.0
1                  Mouse           60000.0
2                Teclado           60000.0
3                  Silla          112500.0
4             Escritorio          135000.0
5                Monitor          330000.0
6              Impresora          245000.0
7                Celular         1000000.0
8              Audifonos           90000.0
9                 Camara          360000.0
10                Router          150000.0
11             Microfono           75000.0
12             Parlantes          140000.0
13            Disco Duro          225000.0
14           Memoria USB           50000.0
15            Smartwatch          225000.0
16             Proyector          300000.0
17                Switch          105000.0
18              Servidor          700000.0
19                Webcam           99000.0
20              Cargador           49000.0
21                 Drone          450000.0
22                   CPU          550000.0
23       Tarjeta Grafica          640000.0
24            Procesador          540000.0
25          Fuente Poder          180000.0
26         Ventilador PC           90000.0
27                   SSD          300000.0
28                   RAM          210000.0
29            Cable HDMI           50000.0
30             Cable USB           45000.0
31             Mouse Pad           22500.0
32           Silla Gamer          170000.0
33            Mesa Gamer          180000.0
34          Pantalla LED          375000.0
35              Joystick          140000.0
36               Consola          560000.0
37          Laptop Gamer          650000.0
38               MacBook          800000.0
39                  iPad          675000.0
40                iPhone         1100000.0
41            Samsung TV          480000.0
42                 Alexa          125000.0
43           Google Home          120000.0
44           Apple Watch          450000.0
45                  Xbox          500000.0
46           PlayStation          450000.0
47       Nintendo Switch          550000.0
48         Monitor Curvo          510000.0
49         Teclado Gamer           90000.0
50           Mouse Gamer           99000.0
51         Camara Web HD           87500.0
52               Escaner          150000.0
53                   UPS          135000.0
54         Servidor Dell          850000.0
55        Router TP-Link          180000.0
56          Impresora HP          225000.0
57         Tablet Lenovo          260000.0
58      Bocina Bluetooth           98000.0
59  Lector Codigo Barras          130000.0

In [ ]:
# =========================================================
# PORCENTAJE DE VENTAS
# =========================================================

# Se calcula el total general de ventas
total_general = df['Total_Venta'].sum()

# Se calcula el porcentaje que representa
# cada producto respecto al total
df['Porcentaje_Ventas'] = (
    df['Total_Venta'] / total_general
) * 100

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("PORCENTAJE DE VENTAS")

# Línea decorativa
print("===================================")

# Mostramos Producto y Porcentaje_Ventas
display(df[['Producto', 'Porcentaje_Ventas']])

===================================
PORCENTAJE DE VENTAS
===================================

                Producto  Porcentaje_Ventas
0                 Laptop           3.798670
1                  Mouse           0.325600
2                Teclado           0.325600
3                  Silla           0.610501
4             Escritorio           0.732601
5                Monitor           1.790802
6              Impresora           1.329535
7                Celular           5.426672
8              Audifonos           0.488400
9                 Camara           1.953602
10                Router           0.814001
11             Microfono           0.407000
12             Parlantes           0.759734
13            Disco Duro           1.221001
14           Memoria USB           0.271334
15            Smartwatch           1.221001
16             Proyector           1.628002
17                Switch           0.569801
18              Servidor           3.798670
19                Webcam           0.537241
20              Cargador           0.265907
21                 Drone           2.442002
22                   CPU           2.984670
23       Tarjeta Grafica           3.473070
24            Procesador           2.930403
25          Fuente Poder           0.976801
26         Ventilador PC           0.488400
27                   SSD           1.628002
28                   RAM           1.139601
29            Cable HDMI           0.271334
30             Cable USB           0.244200
31             Mouse Pad           0.122100
32           Silla Gamer           0.922534
33            Mesa Gamer           0.976801
34          Pantalla LED           2.035002
35              Joystick           0.759734
36               Consola           3.038936
37          Laptop Gamer           3.527337
38               MacBook           4.341338
39                  iPad           3.663004
40                iPhone           5.969339
41            Samsung TV           2.604803
42                 Alexa           0.678334
43           Google Home           0.651201
44           Apple Watch           2.442002
45                  Xbox           2.713336
46           PlayStation           2.442002
47       Nintendo Switch           2.984670
48         Monitor Curvo           2.767603
49         Teclado Gamer           0.488400
50           Mouse Gamer           0.537241
51         Camara Web HD           0.474834
52               Escaner           0.814001
53                   UPS           0.732601
54         Servidor Dell           4.612671
55        Router TP-Link           0.976801
56          Impresora HP           1.221001
57         Tablet Lenovo           1.410935
58      Bocina Bluetooth           0.531814
59  Lector Codigo Barras           0.705467

In [ ]:
# =========================================================
# PRODUCTOS CON PORCENTAJE MAYOR AL 15%
# =========================================================

# Se filtran únicamente los productos
# cuyo porcentaje de ventas es superior al 15%
productos_superiores = (
    df[df['Porcentaje_Ventas'] > 15]
)

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("PRODUCTOS SUPERIORES AL 15%")

# Línea decorativa
print("===================================")

# Mostramos únicamente:
# Producto y Porcentaje_Ventas
print(
    productos_superiores[
        ['Producto', 'Porcentaje_Ventas']
    ]
)

===================================
PRODUCTOS SUPERIORES AL 15%
===================================
Empty DataFrame
Columns: [Producto, Porcentaje_Ventas]
Index: []

In [ ]:
# =========================================================
# MEDIANA DE PRECIO
# =========================================================

# La mediana representa el valor central
# de todos los precios ordenados

mediana_precio = df['Precio'].median()

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("MEDIANA DE PRECIO")

# Línea decorativa
print("===================================")

# Mostramos la mediana
print(mediana_precio)

===================================
MEDIANA DE PRECIO
===================================
725000.0

In [ ]:
# =========================================================
# MEDIANA DE PRECIO
# =========================================================

# La mediana representa el valor central
# de todos los precios ordenados

mediana_precio = df['Precio'].median()

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("MEDIANA DE PRECIO")

# Línea decorativa
print("===================================")

# Mostramos la mediana
print(mediana_precio)

===================================
MEDIANA DE PRECIO
===================================
725000.0

In [ ]:
# =========================================================
# MODA DE PRECIO
# =========================================================

# La moda representa el valor
# que más se repite

moda_precio = df['Precio'].mode()

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("MODA DE PRECIO")

# Línea decorativa
print("===================================")

# Mostramos la moda
display(moda_precio)

===================================
MODA DE PRECIO
===================================

0     250000
1     350000
2     450000
3     900000
4    1800000
Name: Precio, dtype: int64

In [ ]:
# =========================================================
# DESVIACION ESTANDAR
# =========================================================

# La desviación estándar mide
# qué tan dispersos están los datos

desviacion = df['Cantidad'].std()

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("DESVIACION ESTANDAR")

# Línea decorativa
print("===================================")

# Mostramos resultado
print(desviacion)

===================================
DESVIACION ESTANDAR
===================================
5.50028247862169

In [ ]:
# =========================================================
# MAXIMO Y MINIMO
# =========================================================

# Valor máximo de ventas
maximo = df['Total_Venta'].max()

# Valor mínimo de ventas
minimo = df['Total_Venta'].min()

# Mostrar valor máximo
print("\n===================================")

# Mostramos subtítulo
print("VALOR MAXIMO")

# Línea decorativa
print("===================================")

# Mostramos valor máximo
print(maximo)

# Mostrar valor mínimo
print("\n===================================")

# Mostramos subtítulo
print("VALOR MINIMO")

# Línea decorativa
print("===================================")

# Mostramos valor mínimo
print(minimo)

===================================
VALOR MAXIMO
===================================
22000000

===================================
VALOR MINIMO
===================================
450000

In [ ]:
# =========================================================
# EXPLICACION ESTADISTICA
# =========================================================

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("EXPLICACION ESTADISTICA")

# Línea decorativa
print("===================================")

# Explicación de cada concepto
print("La media representa el promedio de los precios.")

print("La mediana representa el valor central.")

print("La moda representa el valor que más se repite.")

print("La desviación estándar mide la dispersión de los datos.")

print("El valor máximo representa la venta más alta.")

print("El valor mínimo representa la venta más baja.")

===================================
EXPLICACION ESTADISTICA
===================================
La media representa el promedio de los precios.
La mediana representa el valor central.
La moda representa el valor que más se repite.
La desviación estándar mide la dispersión de los datos.
El valor máximo representa la venta más alta.
El valor mínimo representa la venta más baja.

In [ ]:
# =========================================================
# FILTRAR CATEGORIA TECNOLOGIA
# =========================================================

# Se filtran únicamente
# los productos de tecnología

tecnologia = df[df['Categoria'] == 'Tecnología']

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("PRODUCTOS TECNOLOGIA")

# Línea decorativa
print("===================================")

# Mostramos productos filtrados
display(tecnologia)

===================================
PRODUCTOS TECNOLOGIA
===================================

,Producto,Precio,Cantidad,Costo_Envio,Categoria,Total_Venta,Costo_Total,IVA,Ganancia_Estimada,Perdida_Estimada,Porcentaje_Ventas
0,Laptop,3500000,4,50000,Tecnología,14000000,14050000,2660000.0,3500000.0,700000.0,3.798670
1,Mouse,80000,15,10000,Tecnología,1200000,1210000,228000.0,300000.0,60000.0,0.325600
2,Teclado,120000,10,12000,Tecnología,1200000,1212000,228000.0,300000.0,60000.0,0.325600
5,Monitor,1100000,6,35000,Tecnología,6600000,6635000,1254000.0,1650000.0,330000.0,1.790802
6,Impresora,700000,7,25000,Tecnología,4900000,4925000,931000.0,1225000.0,245000.0,1.329535
7,Celular,2500000,8,45000,Tecnología,20000000,20045000,3800000.0,5000000.0,1000000.0,5.426672
8,Audifonos,150000,12,10000,Tecnología,1800000,1810000,342000.0,450000.0,90000.0,0.488400
9,Camara,1800000,4,40000,Tecnología,7200000,7240000,1368000.0,1800000.0,360000.0,1.953602
10,Router,300000,10,15000,Tecnología,3000000,3015000,570000.0,750000.0,150000.0,0.814001
11,Microfono,250000,6,12000,Tecnología,1500000,1512000,285000.0,375000.0,75000.0,0.407000
12,Parlantes,400000,7,18000,Tecnología,2800000,2818000,532000.0,700000.0,140000.0,0.759734
13,Disco Duro,500000,9,20000,Tecnología,4500000,4520000,855000.0,1125000.0,225000.0,1.221001
14,Memoria USB,50000,20,5000,Tecnología,1000000,1005000,190000.0,250000.0,50000.0,0.271334
15,Smartwatch,900000,5,25000,Tecnología,4500000,4525000,855000.0,1125000.0,225000.0,1.221001
16,Proyector,2000000,3,50000,Tecnología,6000000,6050000,1140000.0,1500000.0,300000.0,1.628002
17,Switch,350000,6,15000,Tecnología,2100000,2115000,399000.0,525000.0,105000.0,0.569801
18,Servidor,7000000,2,80000,Tecnología,14000000,14080000,2660000.0,3500000.0,700000.0,3.798670
19,Webcam,180000,11,10000,Tecnología,1980000,1990000,376200.0,495000.0,99000.0,0.537241
20,Cargador,70000,14,7000,Tecnología,980000,987000,186200.0,245000.0,49000.0,0.265907
21,Drone,4500000,2,60000,Tecnología,9000000,9060000,1710000.0,2250000.0,450000.0,2.442002
22,CPU,2200000,5,35000,Tecnología,11000000,11035000,2090000.0,2750000.0,550000.0,2.984670
23,Tarjeta Grafica,3200000,4,45000,Tecnología,12800000,12845000,2432000.0,3200000.0,640000.0,3.473070
24,Procesador,1800000,6,30000,Tecnología,10800000,10830000,2052000.0,2700000.0,540000.0,2.930403
25,Fuente Poder,450000,8,12000,Tecnología,3600000,3612000,684000.0,900000.0,180000.0,0.976801
26,Ventilador PC,120000,15,8000,Tecnología,1800000,1808000,342000.0,450000.0,90000.0,0.488400
27,SSD,600000,10,15000,Tecnología,6000000,6015000,1140000.0,1500000.0,300000.0,1.628002
28,RAM,350000,12,10000,Tecnología,4200000,4210000,798000.0,1050000.0,210000.0,1.139601
29,Cable HDMI,40000,25,3000,Tecnología,1000000,1003000,190000.0,250000.0,50000.0,0.271334
30,Cable USB,30000,30,3000,Tecnología,900000,903000,171000.0,225000.0,45000.0,0.244200
31,Mouse Pad,25000,18,2000,Tecnología,450000,452000,85500.0,112500.0,22500.0,0.122100
34,Pantalla LED,1500000,5,40000,Tecnología,7500000,7540000,1425000.0,1875000.0,375000.0,2.035002
35,Joystick,350000,8,12000,Tecnología,2800000,2812000,532000.0,700000.0,140000.0,0.759734
36,Consola,2800000,4,50000,Tecnología,11200000,11250000,2128000.0,2800000.0,560000.0,3.038936
37,Laptop Gamer,6500000,2,70000,Tecnología,13000000,13070000,2470000.0,3250000.0,650000.0,3.527337
38,MacBook,8000000,2,80000,Tecnología,16000000,16080000,3040000.0,4000000.0,800000.0,4.341338
39,iPad,4500000,3,60000,Tecnología,13500000,13560000,2565000.0,3375000.0,675000.0,3.663004
40,iPhone,5500000,4,65000,Tecnología,22000000,22065000,4180000.0,5500000.0,1100000.0,5.969339
41,Samsung TV,3200000,3,45000,Tecnología,9600000,9645000,1824000.0,2400000.0,480000.0,2.604803
42,Alexa,250000,10,10000,Tecnología,2500000,2510000,475000.0,625000.0,125000.0,0.678334
43,Google Home,300000,8,12000,Tecnología,2400000,2412000,456000.0,600000.0,120000.0,0.651201
44,Apple Watch,1800000,5,30000,Tecnología,9000000,9030000,1710000.0,2250000.0,450000.0,2.442002
45,Xbox,2500000,4,45000,Tecnología,10000000,10045000,1900000.0,2500000.0,500000.0,2.713336
46,PlayStation,3000000,3,50000,Tecnología,9000000,9050000,1710000.0,2250000.0,450000.0,2.442002
47,Nintendo Switch,2200000,5,40000,Tecnología,11000000,11040000,2090000.0,2750000.0,550000.0,2.984670
48,Monitor Curvo,1700000,6,38000,Tecnología,10200000,10238000,1938000.0,2550000.0,510000.0,2.767603
49,Teclado Gamer,200000,9,12000,Tecnología,1800000,1812000,342000.0,450000.0,90000.0,0.488400
50,Mouse Gamer,180000,11,12000,Tecnología,1980000,1992000,376200.0,495000.0,99000.0,0.537241
51,Camara Web HD,250000,7,18000,Tecnología,1750000,1768000,332500.0,437500.0,87500.0,0.474834
52,Escaner,600000,5,25000,Tecnología,3000000,3025000,570000.0,750000.0,150000.0,0.814001
53,UPS,900000,3,30000,Tecnología,2700000,2730000,513000.0,675000.0,135000.0,0.732601
54,Servidor Dell,8500000,2,85000,Tecnología,17000000,17085000,3230000.0,4250000.0,850000.0,4.612671
55,Router TP-Link,450000,8,15000,Tecnología,3600000,3615000,684000.0,900000.0,180000.0,0.976801
56,Impresora HP,750000,6,28000,Tecnología,4500000,4528000,855000.0,1125000.0,225000.0,1.221001
57,Tablet Lenovo,1300000,4,32000,Tecnología,5200000,5232000,988000.0,1300000.0,260000.0,1.410935
58,Bocina Bluetooth,280000,7,15000,Tecnología,1960000,1975000,372400.0,490000.0,98000.0,0.531814
59,Lector Codigo Barras,520000,5,18000,Tecnología,2600000,2618000,494000.0,650000.0,130000.0,0.705467

In [ ]:
# =========================================================
# ORDENAR PRODUCTOS
# =========================================================

# Se ordenan los productos
# desde la mayor venta hasta la menor

ordenados = df.sort_values(
    by='Total_Venta',
    ascending=False
)

# Mostrar resultados
print("\n===================================")

# Mostramos subtítulo
print("PRODUCTOS ORDENADOS")

# Línea decorativa
print("===================================")

# Mostramos productos ordenados
display(ordenados[['Producto', 'Total_Venta']])

===================================
PRODUCTOS ORDENADOS
===================================

                Producto  Total_Venta
40                iPhone     22000000
7                Celular     20000000
54         Servidor Dell     17000000
38               MacBook     16000000
18              Servidor     14000000
0                 Laptop     14000000
39                  iPad     13500000
37          Laptop Gamer     13000000
23       Tarjeta Grafica     12800000
36               Consola     11200000
22                   CPU     11000000
47       Nintendo Switch     11000000
24            Procesador     10800000
48         Monitor Curvo     10200000
45                  Xbox     10000000
41            Samsung TV      9600000
46           PlayStation      9000000
44           Apple Watch      9000000
21                 Drone      9000000
34          Pantalla LED      7500000
9                 Camara      7200000
5                Monitor      6600000
27                   SSD      6000000
16             Proyector      6000000
57         Tablet Lenovo      5200000
6              Impresora      4900000
15            Smartwatch      4500000
13            Disco Duro      4500000
56          Impresora HP      4500000
28                   RAM      4200000
55        Router TP-Link      3600000
33            Mesa Gamer      3600000
25          Fuente Poder      3600000
32           Silla Gamer      3400000
10                Router      3000000
52               Escaner      3000000
35              Joystick      2800000
12             Parlantes      2800000
4             Escritorio      2700000
53                   UPS      2700000
59  Lector Codigo Barras      2600000
42                 Alexa      2500000
43           Google Home      2400000
3                  Silla      2250000
17                Switch      2100000
50           Mouse Gamer      1980000
19                Webcam      1980000
58      Bocina Bluetooth      1960000
26         Ventilador PC      1800000
8              Audifonos      1800000
49         Teclado Gamer      1800000
51         Camara Web HD      1750000
11             Microfono      1500000
1                  Mouse      1200000
2                Teclado      1200000
14           Memoria USB      1000000
29            Cable HDMI      1000000
20              Cargador       980000
30             Cable USB       900000
31             Mouse Pad       450000

In [ ]:
# =========================================================
# EXPORTAR A EXCEL
# =========================================================

# Exportamos el DataFrame final
# a un archivo Excel
df.to_excel(
    'resultado_final_pandas.xlsx',
    index=False
)

# Mostramos línea decorativa
print("===================================")

# Mostramos subtítulo
print("ARCHIVO EXPORTADO")

# Mostramos línea decorativa
print("===================================")

# Mostramos mensaje de confirmación
print("Archivo Excel exportado correctamente")

===================================
ARCHIVO EXPORTADO
===================================
Archivo Excel exportado correctamente

In [ ]:
# =========================================================
# DESCARGAR ARCHIVO EXCEL
# =========================================================

# Importamos files para descargar archivos
from google.colab import files

# Descargamos el archivo Excel generado
files.download("resultado_final_pandas.xlsx")